-------------- Таблицы --------------

--DROP TABLE Addresses;
--DROP TABLE Contacts;
--DROP TABLE Flats;
--DROP TABLE Houses;
--DROP TABLE Owners;
--DROP TABLE PhoneNumbers;
--DROP TABLE Porches;
--DROP TABLE Users;

--1. Таблица "Addresses"
CREATE TABLE Addresses (
   AddressId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   Country NVARCHAR2(20) NOT NULL,
   City NVARCHAR2(20) NOT NULL,
   District NVARCHAR2(30),
   Street NVARCHAR2(30) NOT NULL,
   HouseNumber NUMBER NOT NULL,
   HousingNumber NVARCHAR2(5),
   CONSTRAINT PK_Addresses PRIMARY KEY (AddressId)
);

--2. Таблица "Contacts"
CREATE TABLE Contacts (
   ContactId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   Surname NVARCHAR2(30),
   Name NVARCHAR2(20),
   Patronymic NVARCHAR2(20),
   Position NVARCHAR2(20) NOT NULL,
   PhoneNumberId NUMBER NOT NULL,
   UserId NUMBER NOT NULL,
    CONSTRAINT PK_Contacts PRIMARY KEY (ContactId)
);

--3. Таблица "Flats"
CREATE TABLE Flats (
   FlatId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   FlatNumber NUMBER NOT NULL,
   PorchId NUMBER NOT NULL,
   CONSTRAINT PK_Flats PRIMARY KEY (FlatId)
);

--4. Таблица "Houses"
CREATE TABLE Houses (
   HouseId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   HouseName NVARCHAR2(20) NOT NULL,
   NumberOfFlats NUMBER NOT NULL,
   NumberOfPorches NUMBER NOT NULL,
   AddressId NUMBER NOT NULL,
   UserId NUMBER NOT NULL,
   CONSTRAINT PK_Houses PRIMARY KEY (HouseId)
);

--5. Таблица "Owners"
CREATE TABLE Owners (
   OwnerId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   Surname NVARCHAR2(30) NOT NULL,
   Name NVARCHAR2(20) NOT NULL,
   Patronymic NVARCHAR2(20),
   AdditionalInfo NVARCHAR2(30),
   CurrentDebt NUMBER NOT NULL,
   PhoneNumberId NUMBER NOT NULL,
   OwnerStatusId NUMBER NOT NULL,
   FlatId NUMBER NOT NULL,
   CONSTRAINT PK_Owners PRIMARY KEY (OwnerId)
);

--6. Таблица "PhoneNumbers"
CREATE TABLE PhoneNumbers (
  PhoneNumberId      NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
  MobilePhone        NVARCHAR2(20),
  HomePhone          NVARCHAR2(20),
  AdditionalPhone    NVARCHAR2(20),
  CONSTRAINT PK_PhoneNumbers PRIMARY KEY (PhoneNumberId)
);

--7. Таблица "Porches"
CREATE TABLE Porches(
  PorchId INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PorchNumber INTEGER NOT NULL,
  HouseId INTEGER NOT NULL,
  CONSTRAINT PK_Porches PRIMARY KEY (PorchId)
);

--8. Таблица "Users"
CREATE TABLE Users (
   UserId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   Surname NVARCHAR2(30) NOT NULL,
   Name NVARCHAR2(20) NOT NULL,
   Patronymic NVARCHAR2(20),
   Login NVARCHAR2(20) NOT NULL UNIQUE,
   Password NVARCHAR2(40) NOT NULL,
   Role NUMBER NOT NULL,
   AccountantId NUMBER,
   CONSTRAINT PK_Users PRIMARY KEY (UserId)
);

-------------- Ограничения целостности --------------

--ALTER TABLE Contacts DROP CONSTRAINT PhoneNumbers_PhoneNumberId;
--ALTER TABLE Contacts DROP CONSTRAINT Users_UserId;
--ALTER TABLE Flats DROP CONSTRAINT Porches_PorchId;
--ALTER TABLE Houses DROP CONSTRAINT Addresses_AddressId;
--ALTER TABLE Houses DROP CONSTRAINT Houses_UserId;
--ALTER TABLE Houses DROP CONSTRAINT UQ_Houses_UserId_AddressId;
--ALTER TABLE Owners DROP CONSTRAINT Flats_FlatId;
--ALTER TABLE Owners DROP CONSTRAINT Owners_PhoneNumberId;
--ALTER TABLE Porches DROP CONSTRAINT Houses_HouseId;

ALTER TABLE Contacts ADD CONSTRAINT PhoneNumbers_PhoneNumberId FOREIGN KEY (PhoneNumberId) REFERENCES PhoneNumbers(PhoneNumberId) ON DELETE CASCADE;

ALTER TABLE Contacts ADD CONSTRAINT Users_UserId FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE;

ALTER TABLE Flats ADD CONSTRAINT Porches_PorchId FOREIGN KEY (PorchId) REFERENCES Porches(PorchId) ON DELETE CASCADE;

ALTER TABLE Houses ADD CONSTRAINT Addresses_AddressId FOREIGN KEY (AddressId) REFERENCES Addresses(AddressId) ON DELETE CASCADE;

ALTER TABLE Houses ADD CONSTRAINT Houses_UserId FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE;

ALTER TABLE Houses ADD CONSTRAINT UQ_Houses_UserId_AddressId UNIQUE (UserId, AddressId);

ALTER TABLE Owners ADD CONSTRAINT Flats_FlatId FOREIGN KEY (FlatId) REFERENCES Flats(FlatId) ON DELETE CASCADE;

ALTER TABLE Owners ADD CONSTRAINT Owners_PhoneNumberId FOREIGN KEY (PhoneNumberId) REFERENCES PhoneNumbers(PhoneNumberId) ON DELETE CASCADE;

ALTER TABLE Porches ADD CONSTRAINT Houses_HouseId FOREIGN KEY (HouseId) REFERENCES Houses(HouseId) ON DELETE CASCADE;